### PR TITLE
Fix version comparison for deno 1.0.0-rc1

### PR DESCRIPTION
**Pull request by homburg**
Fix install of version 1.0.0-rc1

Also fix ascii colors for macOS bash

### CODE REVIEW

**Comment by imbsky** [comment]
Thanks @homburg!

**Comment by imbsky** [comment]
and the `list-all` also needed to be fixed, so I fixed it with another commit.

**Comment by homburg** [comment]
@imbsky You're welcome!

Was just pushing a `list-all` fix as well :-)

**Comment by imbsky** [comment]
@all-contributors please add @homburg for code

**Pull request merged**
